name: keep streamlit app awake

on:
  schedule:
  - cron: "*/5 * * * *" # checks every 5 minutes
  workflow_dispatch: # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: ping app
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://textsentinel.streamlit.app
